name: Spektra Testsuite Workflow
on: push
jobs:
  build:
   runs-on: ubuntu-latest 
   strategy:
        matrix:
          node: [6, 8, 10]
   steps:
    - name: Run Jest
      uses: stefanoeb/jest-action@1.0.0