name: Spektra Testsuite Workflow
on: push
jobs:
  build:
   runs-on: ubuntu-latest 
   strategy:
        matrix:
          node: [6, 8, 10]
   steps:
      - name: Setting up node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: Installing node dependencies
        run: npm install
      - name: Running Tests
        run: npm run test
    